### ISSUE TITLE
US-05: finish an occupied table

### ISSUE THREAD

**Issue by EMERIC237** [EMERIC237/Restaurant-reservation-app#3]
migration file "20210909195521_createTablesTable.js" failed
migration failed with error: alter table "tables" add constraint "tables_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("reservation_id") on delete cascade - column "reservation_id" referenced in foreign key constraint does not existerror: alter table "tables" add constraint "tables_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("reservation_id") on delete cascade - column "reservation_id" referenced in foreign key constraint does not exist
    at Parser.parseErrorMessage (C:\Users\mycro\Desktop\FinalCapstone\Restaurant-reservation-app\back-end\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\mycro\Desktop\FinalCapstone\Restaurant-reservation-app\back-end\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\mycro\Desktop\FinalCapstone\Restaurant-reservation-app\back-end\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\mycro\Desktop\FinalCapstone\Restaurant-reservation-app\back-end\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by EMERIC237** [comment]
I figured it out. the foreign Id needed to be declared and unsigned
